version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: to-high-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=to-high

volumes:
  mongodb_data:
